from app.services.gmail_service import GmailService, GmailServiceError


def main():
    try:
        draft = GmailService.create_draft(
            recipient_email="kshiti392000@gmail.com",
            subject="JobReach AI Gmail Test",
            body="""
Hello,

This is my first Gmail draft generated by JobReach AI.

If you are reading this in Gmail Drafts, the Gmail API integration is working successfully.

Regards,
JobReach AI
""".strip(),
        )

        print("\n✅ Draft created successfully!")
        print(f"Draft ID   : {draft['id']}")
        print(f"Message ID : {draft['message']['id']}")
        print(f"Thread ID  : {draft['message']['threadId']}")

    except GmailServiceError as exc:
        print(exc)


if __name__ == "__main__":
    main()